name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2

      - name: Installing Node.js â›½
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install and Build ðŸ”§
        run: |
          npm install
          npm run build

      - name: Generating File 404 âš™ï¸
        run: |
          cp dist/404/index.html dist/404.html
          rm -rf dist/404

      - name: Minify build code âš™ï¸
        uses: docker://devatherock/minify-js:latest
        with:
          directory: "dist"
          output: "build"

      - name: Brotli Compress ðŸ—œï¸
        id: brotli
        uses: Charlesworth/compress-action@1.0.0
        with:
          target-directory: "build"

      - name: Configure CNAME ðŸŒ
        run: |
          echo "kelulusan.smkn1pml.sch.id" > CNAME

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build
